### ISSUE TITLE
Todo, Ideas

### ISSUE THREAD

**Issue by Knight1** [ntimo/hcloud-windows#2]
**Fixes**
- [ ] Migrate from servername to ID; More then 1 ID? = Display dialog
- [ ] License
- [ ] Make dc and typ dynamic
- [ ] Support for more then one SSH Key

**Ideas**

- [ ] Upgrade only RAM & CPU within CLI
- [ ] More than dynv6.com Support
- [ ] If Snapshot is too big for the server-type the creation will fail
- [ ] Automation
- [ ] cloudinit
- [ ] HTML5 console opening inside bash
- [ ] Ideen for Smartphone Usage :o

**Done**

- [x] Use the recovery system
- [x] .env
- [x] Comment is hardcoded Windows
- [x] RDP Tutorial
- [ ] hosts File
- [x] RDP Links for every Device
- [x] datacenter type to name
- [x] type via variable
- Should we check if a label called "managed" exists?

**Comment by ntimo** [comment]
- Delete old Snapshot, only keeping the latest one.
